
DROP TABLE IF EXISTS customer, credit_application CASCADE;

CREATE TABLE customer
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    national_identity_number VARCHAR(11) UNIQUE NOT NULL ,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    monthly_income DOUBLE PRECISION NOT NULL,
    gender    VARCHAR(10),
    age       INT DEFAULT 0,
    phone     VARCHAR(15) NOT NULL,
    email     VARCHAR(25) UNIQUE
);

CREATE TABLE credit_application
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credit_application_date DATE NOT NULL,
    credit_result VARCHAR NOT NULL,
    credit_limit DECIMAL NOT NULL,
    customer_id INT NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);




INSERT INTO customer (national_identity_number,name,surname,monthly_income,gender,age,phone,email)
VALUES
    ('16419939227','Fleur','Campbell',19327.69,'FEMALE',84,'57586137967','campbell7937@outlook.edu'),
    ('68716983955','Orli','Hatfield',18713.78,'MALE.',21,'25187466673','hatfield5079@outlook.com'),
    ('91740498566','Finn','Hicks',14635.70, 'FEMALE',59,'86242204768','hicks655@protonmail.couk'),
    ('53179906110','Nash','Pate', 35123.07,'MALE',20,'40284123316','pate@protonmail.com'),
    ('69726904564','Tana','Hogan', 27671.63 ,'FEMALE,',19,'62847241498','hogan4378@google.com'),
    ('50347966878','Catherine','Christensen',47633.07,'FEMALE',88,'67813439628','christensen940@yahoo.org'),
    ('67166158484','Vera','Joyner',15919.19,'FEMALE',19,'14822347386','joyner1629@aol.com'),
    ('30225975999','Kyra','Brown',14500.48,'FEMALE',89,'33628125784','brown4671@yahoo.ca'),
    ('80368440585','Xena','Roman',14289.79,'FEMALE',46,'20026582551','roman@aol.couk'),
    ('44100219190','Hayes','Guzman',19391.28,'MALE',22,'17325470330','guzman@google.net');


INSERT INTO credit_application (credit_application_date,credit_result,credit_limit,customer_id)
VALUES
    ('16-02-2022','REJECTED',0.00,1),
    ('17-02-2022','REJECTED',0.00,2),
    ('26-02-2022','APPROVED',10069.76,3),
    ('26-02-2022','REJECTED',0.00,10),
    ('23-02-2022','APPROVED',65871.95,8),
    ('24-02-2022','REJECTED',0.00,9),
    ('26-02-2022','APPROVED',53683.55,7),
    ('22-02-2022','APPROVED',22795.71,6),
    ('13-02-2022','REJECTED',0.00,5),
    ('23-02-2022','APPROVED',30596.89,4),
    ('22-02-2022','APPROVED',36243.60,8),
    ('25-02-2022','APPROVED',41970.50,4),
    ('18-02-2022','APPROVED',14472.58,6),
    ('23-02-2022','APPROVED',30461.99,3),
    ('25-02-2022','APPROVED',67620.60,2);




